- build: 0.7.0
  image:
    - mesoscloud/events:0.7.0
    - mesoscloud/events:latest

- build: 0.6.1
  image:
    - mesoscloud/events:0.6.1

- build: 0.6.0
  image:
    - mesoscloud/events:0.6.0

- build: 0.5.6
  image:
    - mesoscloud/events:0.5.6

- build: 0.5.5
  image:
    - mesoscloud/events:0.5.5


- tests:
    - cmd: python -m doctest ./*.py
